export type Country = {
  code: string
  name: string
  phoneCode: string
  phoneLength: number
}

export const countries: Country[] = [
  { code: 'AF', name: 'Afghanistan', phoneCode: '+93', phoneLength: 9 },
  { code: 'AL', name: 'Albania', phoneCode: '+355', phoneLength: 9 },
  { code: 'DZ', name: 'Algeria', phoneCode: '+213', phoneLength: 9 },
  { code: 'AR', name: 'Argentina', phoneCode: '+54', phoneLength: 10 },
  { code: 'AU', name: 'Australia', phoneCode: '+61', phoneLength: 9 },
  { code: 'AT', name: 'Austria', phoneCode: '+43', phoneLength: 10 },
  { code: 'BH', name: 'Bahrain', phoneCode: '+973', phoneLength: 8 },
  { code: 'BD', name: 'Bangladesh', phoneCode: '+880', phoneLength: 10 },
  { code: 'BE', name: 'Belgium', phoneCode: '+32', phoneLength: 9 },
  { code: 'BR', name: 'Brazil', phoneCode: '+55', phoneLength: 11 },
  { code: 'BG', name: 'Bulgaria', phoneCode: '+359', phoneLength: 9 },
  { code: 'CA', name: 'Canada', phoneCode: '+1', phoneLength: 10 },
  { code: 'CL', name: 'Chile', phoneCode: '+56', phoneLength: 9 },
  { code: 'CN', name: 'China', phoneCode: '+86', phoneLength: 11 },
  { code: 'HK', name: 'Hong Kong SAR', phoneCode: '+852', phoneLength: 8 },
  { code: 'CO', name: 'Colombia', phoneCode: '+57', phoneLength: 10 },
  { code: 'CR', name: 'Costa Rica', phoneCode: '+506', phoneLength: 8 },
  { code: 'HR', name: 'Croatia', phoneCode: '+385', phoneLength: 9 },
  { code: 'CY', name: 'Cyprus', phoneCode: '+357', phoneLength: 8 },
  { code: 'CZ', name: 'Czechia', phoneCode: '+420', phoneLength: 9 },
  { code: 'DK', name: 'Denmark', phoneCode: '+45', phoneLength: 8 },
  { code: 'DO', name: 'Dominican Republic', phoneCode: '+1', phoneLength: 10 },
  { code: 'EG', name: 'Egypt', phoneCode: '+20', phoneLength: 10 },
  { code: 'EE', name: 'Estonia', phoneCode: '+372', phoneLength: 8 },
  { code: 'FI', name: 'Finland', phoneCode: '+358', phoneLength: 9 },
  { code: 'FR', name: 'France', phoneCode: '+33', phoneLength: 9 },
  { code: 'DE', name: 'Germany', phoneCode: '+49', phoneLength: 10 },
  { code: 'GR', name: 'Greece', phoneCode: '+30', phoneLength: 10 },
  { code: 'HU', name: 'Hungary', phoneCode: '+36', phoneLength: 9 },
  { code: 'IS', name: 'Iceland', phoneCode: '+354', phoneLength: 7 },
  { code: 'IN', name: 'India', phoneCode: '+91', phoneLength: 10 },
  { code: 'ID', name: 'Indonesia', phoneCode: '+62', phoneLength: 10 },
  { code: 'IE', name: 'Ireland', phoneCode: '+353', phoneLength: 9 },
  { code: 'IL', name: 'Israel', phoneCode: '+972', phoneLength: 9 },
  { code: 'IT', name: 'Italy', phoneCode: '+39', phoneLength: 10 },
  { code: 'JP', name: 'Japan', phoneCode: '+81', phoneLength: 10 },
  { code: 'JO', name: 'Jordan', phoneCode: '+962', phoneLength: 9 },
  { code: 'KE', name: 'Kenya', phoneCode: '+254', phoneLength: 9 },
  { code: 'KR', name: 'Korea, Republic of', phoneCode: '+82', phoneLength: 10 },
  { code: 'KW', name: 'Kuwait', phoneCode: '+965', phoneLength: 8 },
  { code: 'LV', name: 'Latvia', phoneCode: '+371', phoneLength: 8 },
  { code: 'LT', name: 'Lithuania', phoneCode: '+370', phoneLength: 8 },
  { code: 'LU', name: 'Luxembourg', phoneCode: '+352', phoneLength: 9 },
  { code: 'MY', name: 'Malaysia', phoneCode: '+60', phoneLength: 9 },
  { code: 'MT', name: 'Malta', phoneCode: '+356', phoneLength: 8 },
  { code: 'MX', name: 'Mexico', phoneCode: '+52', phoneLength: 10 },
  { code: 'MA', name: 'Morocco', phoneCode: '+212', phoneLength: 9 },
  { code: 'NL', name: 'Netherlands', phoneCode: '+31', phoneLength: 9 },
  { code: 'NZ', name: 'New Zealand', phoneCode: '+64', phoneLength: 9 },
  { code: 'NG', name: 'Nigeria', phoneCode: '+234', phoneLength: 10 },
  { code: 'NO', name: 'Norway', phoneCode: '+47', phoneLength: 8 },
  { code: 'OM', name: 'Oman', phoneCode: '+968', phoneLength: 8 },
  { code: 'PK', name: 'Pakistan', phoneCode: '+92', phoneLength: 10 },
  { code: 'PA', name: 'Panama', phoneCode: '+507', phoneLength: 8 },
  { code: 'PE', name: 'Peru', phoneCode: '+51', phoneLength: 9 },
  { code: 'PH', name: 'Philippines', phoneCode: '+63', phoneLength: 10 },
  { code: 'PL', name: 'Poland', phoneCode: '+48', phoneLength: 9 },
  { code: 'PT', name: 'Portugal', phoneCode: '+351', phoneLength: 9 },
  { code: 'QA', name: 'Qatar', phoneCode: '+974', phoneLength: 8 },
  { code: 'RO', name: 'Romania', phoneCode: '+40', phoneLength: 9 },
  { code: 'RU', name: 'Russian Federation', phoneCode: '+7', phoneLength: 10 },
  { code: 'SA', name: 'Saudi Arabia', phoneCode: '+966', phoneLength: 9 },
  { code: 'RS', name: 'Serbia', phoneCode: '+381', phoneLength: 9 },
  { code: 'SG', name: 'Singapore', phoneCode: '+65', phoneLength: 8 },
  { code: 'SK', name: 'Slovakia', phoneCode: '+421', phoneLength: 9 },
  { code: 'SI', name: 'Slovenia', phoneCode: '+386', phoneLength: 8 },
  { code: 'ZA', name: 'South Africa', phoneCode: '+27', phoneLength: 9 },
  { code: 'ES', name: 'Spain', phoneCode: '+34', phoneLength: 9 },
  { code: 'SE', name: 'Sweden', phoneCode: '+46', phoneLength: 9 },
  { code: 'CH', name: 'Switzerland', phoneCode: '+41', phoneLength: 9 },
  { code: 'TW', name: 'Taiwan', phoneCode: '+886', phoneLength: 9 },
  { code: 'TH', name: 'Thailand', phoneCode: '+66', phoneLength: 9 },
  { code: 'TR', name: 'Türkiye', phoneCode: '+90', phoneLength: 10 },
  { code: 'AE', name: 'United Arab Emirates', phoneCode: '+971', phoneLength: 9 },
  { code: 'GB', name: 'United Kingdom', phoneCode: '+44', phoneLength: 10 },
  { code: 'US', name: 'United States', phoneCode: '+1', phoneLength: 10 },
  { code: 'VN', name: 'Viet Nam', phoneCode: '+84', phoneLength: 9 },
]
